### PR TITLE
Add constrain_angle utility function

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by raulvera59** [comment]
This is a performance regression, and is likely unstable near pi/2. The vast majority of the time this function will be called with a value between -2pi and 2pi, which means that my version would cost two compares if the value is already in range, three compares and an add or subtract if it's out of range but between -2pi and 2pi, and more only in the extremely rare cases when it's outside that. In fact the while loops are only there for defensive purposes. Your version costs three expensive transcendental functions each and every time it's called, even if the value is returned unchanged. Furthermore, if the value is near pi/2, cosine is near 0, so the arctangent is close to a divide by 0. It might work if the value is 0, as that is special cased, but close to 0 I'm not so sure.
And I see that James calls it 3 times per cycle in his estimator, so making this fast might be worthwhile.

**Comment by auscompgeek** [comment]
I wasn't convinced this is a significant regression, so I wrote some pytest/hypothesis tests to measure both the correctness and performance (which I will happily throw in the repo):

```python
import math

import pytest
from hypothesis import given
from hypothesis.strategies import floats


def constrain_angle_atan(angle: float) -> float:
    """Wrap an angle to the interval [-pi,pi]."""
    return math.atan2(math.sin(angle), math.cos(angle))


def constrain_angle_while(angle: float) -> float:
    while angle < -math.pi:
        angle += math.tau
    while angle > math.pi:
        angle -= math.tau
    return angle


@pytest.fixture(params=["atan", "while"])
def constrain_angle(request):
    if request.param == "atan":
        return constrain_angle_atan
    return constrain_angle_while


@given(angle=floats(-math.pi, math.pi))
def test_happy(angle: float, constrain_angle):
    """Test the happy path: the angle is in [-pi,pi]."""
    assert constrain_angle(angle) == pytest.approx(angle)


def test_zero(constrain_angle):
    assert constrain_angle(0) == 0


def test_edge(constrain_angle):
    assert constrain_angle(math.pi) == pytest.approx(math.pi)
    assert constrain_angle(-math.pi) == pytest.approx(-math.pi)


def test_revolution(constrain_angle):
    assert constrain_angle(math.tau) == pytest.approx(0)
    assert constrain_angle(-math.tau) == pytest.approx(0)


@given(angle=floats(-math.tau, -math.pi, exclude_max=True))
def test_one_wrap_positive_half(angle: float, constrain_angle):
    assert constrain_angle(angle) == pytest.approx(angle + math.tau)


@given(angle=floats(math.pi, math.tau, exclude_min=True))
def test_one_wrap_negative_half(angle: float, constrain_angle):
    assert constrain_angle(angle) == pytest.approx(angle - math.tau)
```

I haven't managed to get the tests to fail, and I've only managed to observe a performance difference of about 0.25 us. I think we should worry about performance in other things before we come to this.

**Comment by raulvera59** [comment]
I've run some tests on my laptop, and determined the following:
- My version is only 12% faster. 
- There is no instability near pi/2.
So never mind.

**Comment by auscompgeek** [comment]
Opened #126 to add appropriate tests.

**Pull request merged**
